# Generated by Django 4.2.28 on 2026-02-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('cor_primaria', models.CharField(default='#ef4444', max_length=10)),
                ('cor_secundaria', models.CharField(default='#ffffff', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('whatsapp', models.CharField(help_text='Ex: 5511999999999', max_length=20)),
                ('horario_funcionamento', models.JSONField(default=dict, help_text="Ex: {'seg': '08:00-18:00'}")),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeAtributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RADIO', 'Seleção Única'), ('CHECKBOX', 'Seleção Múltipla')], default='RADIO', max_length=10)),
                ('min_opcoes', models.PositiveIntegerField(default=0)),
                ('max_opcoes', models.PositiveIntegerField(default=1)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configuracaoloja')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.categoria')),
                ('grupos_atributos', models.ManyToManyField(blank=True, to='core.grupodeatributos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_whatsapp', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('PREPARO', 'Em Preparo'), ('DESPACHADO', 'Despachado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='NOVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configuracaoloja')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.configuracaoloja'),
        ),
        migrations.CreateModel(
            name='AtributoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='core.grupodeatributos')),
            ],
        ),
    ]
