# Generated by Django 4.2.28 on 2026-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço físico da loja', null=True),
        ),
    ]
