# Generated by Django 4.2.28 on 2026-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaoloja_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='selecoes',
            field=models.JSONField(default=list, help_text='Lista de atributos selecionados'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('PIX', 'Pix')], default='PIX', max_length=20),
        ),
    ]
