# Generated by Django 4.2.28 on 2026-02-12 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_itempedido_selecoes_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='evolution_instance',
            field=models.CharField(blank=True, help_text='Nome da instância na Evolution API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='evolution_token',
            field=models.CharField(blank=True, help_text='Token da instância', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to=settings.AUTH_USER_MODEL),
        ),
    ]
