# Generated by Django 4.2.28 on 2026-02-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaoloja_evolution_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('max_produtos', models.IntegerField(default=50)),
                ('recursos', models.JSONField(default=dict, help_text="Ex: {'whatsapp': true, 'kanban': true}")),
            ],
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='status_assinatura',
            field=models.CharField(choices=[('trial', 'Teste'), ('active', 'Ativo'), ('expired', 'Expirado'), ('canceled', 'Cancelado')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='valido_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plano'),
        ),
    ]
