# Generated by Django 4.2.28 on 2026-02-12 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_plano_configuracaoloja_status_assinatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuarioLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('manager', 'Gerente'), ('waiter', 'Atendente'), ('kitchen', 'Cozinha'), ('driver', 'Entregador')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='core.configuracaoloja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_lojas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'loja')},
            },
        ),
    ]
