# Generated by Django 4.2.28 on 2026-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilusuarioloja'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
