# Generated by Django 4.2.28 on 2026-02-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracaoloja_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='controlar_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(default=0),
        ),
    ]
