# Generated by Django 4.2.28 on 2026-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_caixa_movimentacaocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada'), ('MESA', 'Mesa')], default='ENTREGA', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
