# Generated by Django 4.2.28 on 2026-02-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedido_mesa_pedido_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuarioloja',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('manager', 'Gerente'), ('waiter', 'Atendente'), ('cashier', 'Operador de Caixa'), ('kitchen', 'Cozinha'), ('driver', 'Entregador')], max_length=20),
        ),
    ]
