# Generated by Django 4.2.28 on 2026-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_perfilusuarioloja_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto'), ('DESPACHADO', 'Despachado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='NOVO', max_length=20),
        ),
    ]
