# Generated by Django 4.2.28 on 2026-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_diario',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
