# Generated by Django 4.2.28 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pedido_numero_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='msg_entrega',
            field=models.TextField(default='Olá {cliente}! 🛵 Seu pedido #{numero} de *{loja}* saiu para entrega! Fique atento(a).', help_text='Variáveis: {cliente}, {numero}, {loja}'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='msg_finalizado',
            field=models.TextField(default='Pedido #{numero} de *{loja}* concluído. Obrigado pela preferência, {cliente}! ⭐', help_text='Variáveis: {cliente}, {numero}, {loja}'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='msg_preparo',
            field=models.TextField(default='Olá {cliente}! 👨\u200d🍳 Seu pedido #{numero} começou a ser preparado em *{loja}*. Em breve avisaremos quando sair para entrega!', help_text='Variáveis: {cliente}, {numero}, {loja}'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='notificar_entrega',
            field=models.BooleanField(default=True, help_text='Notificar cliente quando o pedido sair para entrega'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='notificar_finalizado',
            field=models.BooleanField(default=True, help_text='Notificar cliente quando o pedido for finalizado'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='notificar_preparo',
            field=models.BooleanField(default=True, help_text='Notificar cliente quando o pedido entrar em preparo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto'), ('DESPACHADO', 'Entrega'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='NOVO', max_length=20),
        ),
    ]
