# Generated by Django 4.2.28 on 2026-02-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracaoloja_msg_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada'), ('MESA', 'Mesa'), ('BALCAO', 'Balcão')], default='ENTREGA', max_length=10),
        ),
    ]
