# Generated by Django 4.2.28 on 2026-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pedido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
