# Generated by Django 4.2.28 on 2026-02-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='taxa_entrega_fixa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='tipo_taxa_entrega',
            field=models.CharField(choices=[('FIXA', 'Taxa Fixa Única'), ('BAIRRO', 'Taxa por Bairro')], default='FIXA', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BairroEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros_entrega', to='core.configuracaoloja')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
