# Generated by Django 4.2.28 on 2026-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_configuracaoloja_taxa_entrega_fixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='ifood_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='ifood_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='ifood_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='ifood_merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='ifood_token',
            field=models.TextField(blank=True, help_text='Access Token do iFood', null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='ifood_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID do pedido em plataformas externas (ex: iFood)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origem',
            field=models.CharField(default='APP', help_text='APP, IFOOD, WHATSAPP, etc', max_length=50),
        ),
    ]
