# Generated by Django 5.2.8 on 2026-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configuracaoloja_ifood_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='mp_plan_id',
            field=models.CharField(blank=True, help_text='ID do Plano no Mercado Pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, help_text='ID da Assinatura no Mercado Pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='plano_tipo',
            field=models.CharField(choices=[('START', 'Plano Start'), ('PRO', 'Plano Pro'), ('ELITE', 'Plano Elite')], default='START', max_length=20),
        ),
    ]
