# Generated by Django 5.2.8 on 2026-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_configuracaoloja_mp_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='bot_alerta_transbordo',
            field=models.CharField(blank=True, help_text='Critérios para a IA parar de responder e chamar um humano', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='bot_ativo_whatsapp',
            field=models.BooleanField(default=False, help_text='Ativar o Atendente IA no WhatsApp'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='bot_conhecimento',
            field=models.TextField(blank=True, help_text='Regras da casa e base de conhecimento extra', null=True),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='bot_personalidade',
            field=models.CharField(blank=True, help_text='Instruções de tom de voz e personalidade', max_length=500, null=True),
        ),
    ]
