# Generated by Django 5.2.8 on 2026-03-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_notificacaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='modo_catalogo',
            field=models.BooleanField(default=False, help_text='Se ativado, o cardápio funcionará apenas para visualização'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='quantidade_mesas',
            field=models.PositiveIntegerField(default=0, help_text='Número de mesas para geração de QR Codes'),
        ),
    ]
