# Generated by Django 5.2.8 on 2026-03-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_configuracaoloja_modo_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Troco calculado', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor entregue pelo cliente', max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='plano_tipo',
            field=models.CharField(choices=[('START', 'Plano Start'), ('PRO', 'Plano Pro')], default='START', max_length=20),
        ),
    ]
