# Generated by Django 4.2.29 on 2026-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pedido_troco_pedido_valor_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='troco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Troco calculado', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Valor entregue pelo cliente', max_digits=10, null=True),
        ),
    ]
