# Generated by Django 4.2.29 on 2026-03-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_pedido_troco_alter_pedido_valor_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='msg_cancelado',
            field=models.TextField(default='Olá {cliente}. Infelizmente seu pedido #{numero} em *{loja}* precisou ser cancelado. Se tiver dúvidas, entre em contato conosco.', help_text='Variáveis: {cliente}, {numero}, {loja}'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='msg_pronto',
            field=models.TextField(default='Olá {cliente}! ✨ Seu pedido #{numero} está pronto! Se for retirada, já pode vir buscar. Se for entrega, sairá em instantes.', help_text='Variáveis: {cliente}, {numero}, {loja}'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='msg_recebido',
            field=models.TextField(default='Olá {cliente}! 👋 Recebemos seu pedido #{numero} em *{loja}*. Já vamos começar a preparar!', help_text='Variáveis: {cliente}, {numero}, {loja}'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='notificar_cancelado',
            field=models.BooleanField(default=True, help_text='Notificar cliente quando o pedido for cancelado'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='notificar_pronto',
            field=models.BooleanField(default=True, help_text='Notificar cliente quando o pedido estiver pronto'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='notificar_recebido',
            field=models.BooleanField(default=True, help_text='Notificar cliente quando o pedido for recebido'),
        ),
    ]
