# Generated by Django 4.2.29 on 2026-03-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_configuracaoloja_msg_cancelado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='modo_catalogo_mesa',
            field=models.BooleanField(default=False, help_text='Cardápio Mesa apenas visualização'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='permitir_pedido_mesa',
            field=models.BooleanField(default=False, help_text='Habilitar pedidos via QR Code nas mesas'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='modo_catalogo',
            field=models.BooleanField(default=False, help_text='Cardápio Delivery apenas visualização'),
        ),
    ]
