# Generated by Django 4.2.29 on 2026-04-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_configuracaoloja_modo_catalogo_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='crm_dias_ausente',
            field=models.PositiveIntegerField(default=7, help_text='Dias sem pedir para considerar ausente'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='crm_msg_ausente',
            field=models.TextField(blank=True, default='Olá {cliente}! Sentimos sua falta em *{loja}*. Que tal um pedido hoje? 🍕', help_text='Mensagem padrão para clientes ausentes. Variáveis: {cliente}, {loja}', null=True),
        ),
    ]
