# Generated by Django 5.2.8 on 2026-04-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_configuracaoloja_crm_dias_ausente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Notas permanentes sobre este cliente', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_clientes', to='core.configuracaoloja')),
            ],
            options={
                'verbose_name': 'Perfil do Cliente',
                'verbose_name_plural': 'Perfis dos Clientes',
                'unique_together': {('loja', 'whatsapp')},
            },
        ),
    ]
