# Generated by Django 4.2.29 on 2026-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_perfilcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='atendimento_mesas',
            field=models.BooleanField(default=False, help_text='Habilitar o uso de Mesas no sistema'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='crm_dias_ausente',
            field=models.PositiveIntegerField(default=30, help_text='Dias sem pedir para considerar ausente'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='plano_tipo',
            field=models.CharField(choices=[('START', 'Plano Start'), ('PRO', 'Plano Pro'), ('ELITE', 'Plano Elite')], default='START', max_length=20),
        ),
    ]
